# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ays/3A/Calculparall_Para

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ays/3A/Calculparall_Para

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ays/3A/Calculparall_Para/CMakeFiles /home/ays/3A/Calculparall_Para//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ays/3A/Calculparall_Para/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CHP

# Build rule for target.
CHP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CHP
.PHONY : CHP

# fast build rule for target.
CHP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/build
.PHONY : CHP/fast

Matrix.o: Matrix.cpp.o
.PHONY : Matrix.o

# target to build an object file
Matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/Matrix.cpp.o
.PHONY : Matrix.cpp.o

Matrix.i: Matrix.cpp.i
.PHONY : Matrix.i

# target to preprocess a source file
Matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/Matrix.cpp.i
.PHONY : Matrix.cpp.i

Matrix.s: Matrix.cpp.s
.PHONY : Matrix.s

# target to generate assembly for a file
Matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/Matrix.cpp.s
.PHONY : Matrix.cpp.s

charge.o: charge.cpp.o
.PHONY : charge.o

# target to build an object file
charge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/charge.cpp.o
.PHONY : charge.cpp.o

charge.i: charge.cpp.i
.PHONY : charge.i

# target to preprocess a source file
charge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/charge.cpp.i
.PHONY : charge.cpp.i

charge.s: charge.cpp.s
.PHONY : charge.s

# target to generate assembly for a file
charge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/charge.cpp.s
.PHONY : charge.cpp.s

functions.o: functions.cpp.o
.PHONY : functions.o

# target to build an object file
functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/functions.cpp.o
.PHONY : functions.cpp.o

functions.i: functions.cpp.i
.PHONY : functions.i

# target to preprocess a source file
functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/functions.cpp.i
.PHONY : functions.cpp.i

functions.s: functions.cpp.s
.PHONY : functions.s

# target to generate assembly for a file
functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/functions.cpp.s
.PHONY : functions.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/main.cpp.s
.PHONY : main.cpp.s

settings.o: settings.cpp.o
.PHONY : settings.o

# target to build an object file
settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/settings.cpp.o
.PHONY : settings.cpp.o

settings.i: settings.cpp.i
.PHONY : settings.i

# target to preprocess a source file
settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/settings.cpp.i
.PHONY : settings.cpp.i

settings.s: settings.cpp.s
.PHONY : settings.s

# target to generate assembly for a file
settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/settings.cpp.s
.PHONY : settings.cpp.s

solver.o: solver.cpp.o
.PHONY : solver.o

# target to build an object file
solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/solver.cpp.o
.PHONY : solver.cpp.o

solver.i: solver.cpp.i
.PHONY : solver.i

# target to preprocess a source file
solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/solver.cpp.i
.PHONY : solver.cpp.i

solver.s: solver.cpp.s
.PHONY : solver.s

# target to generate assembly for a file
solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CHP.dir/build.make CMakeFiles/CHP.dir/solver.cpp.s
.PHONY : solver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CHP"
	@echo "... Matrix.o"
	@echo "... Matrix.i"
	@echo "... Matrix.s"
	@echo "... charge.o"
	@echo "... charge.i"
	@echo "... charge.s"
	@echo "... functions.o"
	@echo "... functions.i"
	@echo "... functions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... settings.o"
	@echo "... settings.i"
	@echo "... settings.s"
	@echo "... solver.o"
	@echo "... solver.i"
	@echo "... solver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

